name: AWS Connectivity Test

on:
  workflow_dispatch:  # run manually

permissions:
  id-token: write   # required for OIDC federation
  contents: read

jobs:
  aws-test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::555488808142:role/FULL-ACCESS-ADMIN-ROLE
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: List S3 Buckets (simple test)
        run: aws s3 ls
