name: AWS Tiny Test

on:
  workflow_dispatch: # run manually

permissions:
  id-token: write
  contents: read

jobs:
  aws-test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::555488808142:role/FULL-ACCESS-ADMIN-ROLE
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Create Test S3 Bucket
        run: |
          BUCKET_NAME="gha-test-bucket-$RANDOM"
          echo "Creating bucket: $BUCKET_NAME"
          aws s3 mb s3://$BUCKET_NAME --region us-east-1
          echo "bucket_name=$BUCKET_NAME" >> $GITHUB_ENV

      - name: List Buckets
        run: aws s3 ls

